name: hwr_env
channels:
- byu-handwriting-lab
- conda-forge
- defaults
dependencies:
- python=3.7.3
- pip=22.3
- tensorflow-gpu=2.10.0
- numpy=1.21.6
- pyyaml=6.0
- pandas=1.3.5
- matplotlib=3.3.2
- tqdm=4.64.1
- editdistance=0.6.0
- word_beam_search=0.1
- pip:
  - tensorflow-addons==0.18.0
