name: hwr_env
channels:
- defaults
- anaconda
- conda-forge
- byu-handwriting-lab
dependencies:
- python=3.7.3
- anaconda::numpy=1.19.1
- anaconda::tensorflow-gpu=2.1.0
- anaconda::pyyaml=5.3.1
- anaconda::pandas=1.0.3
- conda-forge::matplotlib=3.2.1
- anaconda::tqdm=4.31.1
- conda-forge::editdistance=0.5.3
- byu-handwriting-lab::word_beam_search