package:
  name: hwr
  version: 0.1

source:
  path: ./

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python==3.7.3
    - numpy==1.19.1
    - tensorflow-gpu==2.1.0
    - pyyaml=5.3.1
    - pandas==1.0.3
    - matplotlib==3.2.1
    - tqdm==4.38
  run:
    - python==3.7.3
    - numpy==1.19.1
    - tensorflow-gpu==2.1.0
    - pyyaml=5.3.1
    - pandas==1.0.3
    - matplotlib==3.2.1
    - tqdm==4.38

test:
  imports:
    - hwr

about:
  home: https://github.com/BYU-Handwriting-Lab
